In [1]:
from paraatm.io.iff import read_iff_file
data = read_iff_file('IFF_SFO+ASDEX_20190511_080104_86221.csv')

In [2]:
data

,recType,time,fltKey,bcnCode,cid,Source,msgType,callsign,recTypeCat,latitude,...,activeContr,primaryContr,kybrdSubset,kybrdSymbol,adsCode,opsType,airportCode,trackNumber,tptReturnType,modeSCode
0,3,2019-05-11 07:26:57,26612,2270.0,NaN,0/MODE_S,0xE02,DAL2312,1,37.71159,...,NaN,NaN,NaN,NaN,NaN,NaN,SFO,224,NaN,a98219
1,3,2019-05-11 07:26:58,26612,2270.0,NaN,0/MODE_S,0xE02,DAL2312,1,37.71037,...,NaN,NaN,NaN,NaN,NaN,NaN,SFO,224,NaN,a98219
2,3,2019-05-11 07:27:00,26612,2270.0,NaN,0/MODE_S,0xE02,DAL2312,1,37.70871,...,NaN,NaN,NaN,NaN,NaN,NaN,SFO,224,NaN,a98219
3,3,2019-05-11 07:27:01,26612,2270.0,NaN,0/MODE_S,0xE02,DAL2312,1,37.70776,...,NaN,NaN,NaN,NaN,NaN,NaN,SFO,224,NaN,a98219
4,3,2019-05-11 07:27:02,26612,2270.0,NaN,0/MODE_S,0xE02,DAL2312,1,37.70698,...,NaN,NaN,NaN,NaN,NaN,NaN,SFO,224,NaN,a98219
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1030405,3,2019-05-12 07:53:49,33054,NaN,NaN,0/SFO,0xE02,OPS4,1,37.63029,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1044,NaN,a32beb
1030406,3,2019-05-12 07:53:50,33054,NaN,NaN,0/SFO,0xE02,OPS4,1,37.63035,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1044,NaN,a32beb
1030407,3,2019-05-12 07:53:51,33054,NaN,NaN,0/SFO,0xE02,OPS4,1,37.63041,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1044,NaN,a32beb
1030408,3,2019-05-12 07:53:52,33054,NaN,NaN,0/SFO,0xE02,OPS4,1,37.63047,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1044,NaN,a32beb
1030409,3,2019-05-12 07:53:53,33054,NaN,NaN,0/SFO,0xE02,OPS4,1,37.63052,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1044,NaN,a32beb

In [3]:
import sys
sys.path.append('$HOME/NATS_Standalone_Ubuntu_16.04_Prod1.0/GNATS_Standalone')
sys.path.append('$HOME/NATS_Standalone_Ubuntu_16.04_Prod1.0/GNATS_Standalone/sample')

from FlightPlanSelector import FlightPlanSelector

!!!!!!!!!!!!!!!!!!
Notice
Some GNATS samples use Google map for presentation.  It requires Google map API key.  The key may exceed the maximum quota due to enormous NATS users' activities.
If you experience Google map failure, please edit PathVisualizer.py with a new Google map key obtained from developers.google.com/maps/documentation/javascript/get-api-key
!!!!!!!!!!!!!!!!!!

AttributeError: 'NoneType' object has no attribute 'getControllerInterface'